trigger:
  branches:
    include:
    - master
pr:
- master

variables:
  BuildConfiguration: Release

jobs:
- job: test_utils
  displayName: Test winmd utils
  workspace:
    clean: all
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    lfs: true

  - task: UseDotNet@2
    displayName: ⚙ Install .NET SDK
    inputs:
      packageType: sdk
      useGlobalJson: true

  - task: PowerShell@2
    displayName: Set build version
    inputs:
      targetType: inline
      script: |
        . .\scripts\CommonUtils.ps1
        Install-DotNetTool nbgv
        nbgv cloud
      errorActionPreference: 'continue'
      pwsh: true

  - task: PowerShell@2
    displayName: Test metadata binary
    inputs:
      targetType: inline
      script: |
        dotnet --info
        .\scripts\TestWinmdBinary.ps1 .\scripts\BaselineWinmd\Windows.Win32.test.winmd
      pwsh: true

